program KBusiness;

{ Reduce EXE size by disabling as much of RTTI as possible (delphi 2009/2010) }

{$IF CompilerVersion >= 21.0}

{$WEAKLINKRTTI ON}

{$RTTI EXPLICIT METHODS([]) PROPERTIES([]) FIELDS([])}

{$IFEND}


uses
  Forms,
  PublicPS in 'Public\PublicPS.pas',
  DataPS in 'Public\DataPS.pas' {DataFM: TDataModule},
  LoginPS in 'Public\LoginPS.pas' {LoginFM},
  MainPS in 'MainPS.pas' {MainFM},
  BaseMouldPS in 'Public\BaseMouldPS.pas' {BaseMouldFM},
  StockModulePS in 'Public\StockModulePS.pas' {StockModuleFM},
  WareModulePS in 'Public\WareModulePS.pas' {WareModuleFM},
  InvoiceMouldPS in 'Public\InvoiceMouldPS.pas' {InvoiceMouldFM},
  HRModulePS in 'Public\HRModulePS.pas' {HRModuleFM},
  SaleModulePS in 'Public\SaleModulePS.pas' {SaleModuleFM},
  MainBasePS in 'Public\MainBasePS.pas' {MainBaseFM},
  DataBackPS in 'System\DataBackPS.pas' {DataBackFM},
  BasePS in 'Base\BasePS.pas' {BaseFM},
  AreaPS in 'BaseModule\AreaPS.pas' {AreaFM},
  ReportSetPS in 'System\ReportSetPS.pas' {ReportSetFM},
  ReportPS in 'Public\ReportPS.pas' {ReportFM},
  BaseGrdPS in 'Base\BaseGrdPS.pas' {BaseGrdFM},
  Base1PS in 'Base\Base1PS.pas' {Base1FM},
  SysUserSetPS in 'System\SysUserSetPS.pas' {SysUserSetFM},
  WarePS in 'BaseModule\WarePS.pas' {WareFM},
  PrvKindPS in 'BaseModule\PrvKindPS.pas' {PrvKindFM},
  ProviderPS in 'BaseModule\ProviderPS.pas' {ProviderFM},
  AreaQPS in 'BaseModule\AreaQPS.pas' {AreaQFM},
  PrvKindQPS in 'BaseModule\PrvKindQPS.pas' {PrvKindQFM},
  CustKindPS in 'BaseModule\CustKindPS.pas' {CustKindFM},
  CustPS in 'BaseModule\CustPS.pas' {CustFM},
  CustKindQPS in 'BaseModule\CustKindQPS.pas' {CustKindQFM},
  DeptPS in 'BaseModule\DeptPS.pas' {DeptFM},
  EmployeePS in 'BaseModule\EmployeePS.pas' {EmployeeFM},
  DeptQPS in 'BaseModule\DeptQPS.pas' {DeptQFM},
  EmpQPS in 'BaseModule\EmpQPS.pas' {EmpQFM},
  ItemPS in 'BaseModule\ItemPS.pas' {ItemFM},
  ItemKindQPS in 'BaseModule\ItemKindQPS.pas' {ItemKindQFM},
  WareQPS in 'BaseModule\WareQPS.pas' {WareQFM},
  OtherSetPS in 'BaseModule\OtherSetPS.pas' {OtherSetFM},
  IMCode in 'Public\IMCode.pas',
  UserRightPS in 'System\UserRightPS.pas' {UserRightFM},
  AssistModulePS in 'Public\AssistModulePS.pas' {AssistModuleFM},
  ListSqlServers in 'Public\ListSqlServers.pas',
  ChangePassPS in 'System\ChangePassPS.pas' {ChangePassFM},
  RequirePS in 'Stock\RequirePS.pas' {RequireFM},
  SBasePS in 'BaseModule\SBasePS.pas' {SBaseFM},
  ItemQPS in 'BaseModule\ItemQPS.pas' {ItemQFM},
  SysTableSetPS in 'System\SysTableSetPS.pas' {SysTableSetFM},
  ProduceModulePS in 'Public\ProduceModulePS.pas' {ProduceModuleFM},
  RequireFindPS in 'Stock\RequireFindPS.pas' {RequireFindFM},
  SysParamPS in 'System\SysParamPS.pas' {SysParamFM},
  PrvQPS in 'BaseModule\PrvQPS.pas' {PrvQFM},
  FBasePS in 'Base\FBasePS.pas' {FBaseFM},
  StockOrderFindPS in 'Stock\StockOrderFindPS.pas' {StockOrderFindFM},
  RequireQPS in 'Stock\RequireQPS.pas' {RequireQFM},
  QBasePS in 'Base\QBasePS.pas' {QBaseFM},
  StockOrderQPS in 'Stock\StockOrderQPS.pas' {StockOrderQFM},
  SaleOrderPS in 'Sale\SaleOrderPS.pas' {SaleOrderFM},
  SaleSenderFindPS in 'Sale\SaleSenderFindPS.pas' {SaleSenderFindFM},
  CustQPS in 'BaseModule\CustQPS.pas' {CustQFM},
  SaleOrderQPS in 'Sale\SaleOrderQPS.pas' {SaleOrderQFM},
  SysLogQPS in 'System\SysLogQPS.pas' {SysLogQFM},
  FirstBookPS in 'Ware\FirstBookPS.pas' {FirstBookFM},
  ProTypePS in 'BaseModule\ProTypePS.pas' {ProTypeFM},
  ProTypeQPS in 'BaseModule\ProTypeQPS.pas' {ProTypeQFM},
  RegSetPS in 'Public\RegSetPS.pas' {RegSetFM},
  RegPS in 'Public\RegPS.pas',
  WareInOutFindPS in 'Ware\WareInOutFindPS.pas' {WareInOutFindFM},
  StockPricePS in 'Stock\StockPricePS.pas' {StockPriceFM},
  ColorPS in 'BaseModule\ColorPS.pas' {ColorFM},
  WareMonthAccountPS in 'Ware\WareMonthAccountPS.pas' {WareMonthAccountFM},
  WareInOutPS in 'Ware\WareInOutPS.pas' {WareInOutFM},
  StockInPS in 'Ware\StockInPS.pas' {StockInFM},
  FinanceDatePS in 'System\FinanceDatePS.pas' {FinanceDateFM},
  WareStorageQPS in 'Ware\WareStorageQPS.pas' {WareStorageQFM},
  WareInOutQPS in 'Ware\WareInOutQPS.pas' {WareInOutQFM},
  SFCMonQPS in 'Ware\SFCMonQPS.pas' {SFCMonQFM},
  RBasePS in 'Base\RBasePS.pas' {RBaseFM},
  StockOrderReqRfPS in 'Stock\StockOrderReqRfPS.pas' {StockOrderReqRfFM},
  MatOutPS in 'Ware\MatOutPS.pas' {MatOutFM},
  ProductInPS in 'Ware\ProductInPS.pas' {ProductInFM},
  OtherInPS in 'Ware\OtherInPS.pas' {OtherInFM},
  OtherOutPS in 'Ware\OtherOutPS.pas' {OtherOutFM},
  SalePricePS in 'Sale\SalePricePS.pas' {SalePriceFM},
  WareCheckPS in 'Ware\WareCheckPS.pas' {WareCheckFM},
  WareItemPS in 'BaseModule\WareItemPS.pas' {WareItemFM},
  SaleOutSaleOrderRfPS in 'Ware\SaleOutSaleOrderRfPS.pas' {SaleOutSaleOrderRfFM},
  WareCheckFindPS in 'Ware\WareCheckFindPS.pas' {WareCheckFindFM},
  ItemBomPS in 'BaseModule\ItemBomPS.pas' {ItemBomFM},
  SaleFirstPS in 'Invoice\SaleFirstPS.pas' {SaleFirstFM},
  SaleInvoiceFindPS in 'Invoice\SaleInvoiceFindPS.pas' {SaleInvoicerFindFM},
  SaleInvoicePS in 'Invoice\SaleInvoicePS.pas' {SaleInvoiceFM},
  SaleInvoiceSaleOutRfPS in 'Invoice\SaleInvoiceSaleOutRfPS.pas' {SaleInvoiceSaleOutRfFM},
  SaleMonthAccountPS in 'Invoice\SaleMonthAccountPS.pas' {SaleMonthAccountFM},
  SalePayFindPS in 'Invoice\SalePayFindPS.pas' {SalePayFindFM},
  SalePayInvoiceRfPS in 'Invoice\SalePayInvoiceRfPS.pas' {SalePayInvoiceRfFM},
  SalePayPS in 'Invoice\SalePayPS.pas' {SalePayFM},
  StockFirstPS in 'Invoice\StockFirstPS.pas' {StockFirstFM},
  StockInvoicePS in 'Invoice\StockInvoicePS.pas' {StockInvoiceFM},
  StockInvoiceFindPS in 'Invoice\StockInvoiceFindPS.pas' {StockInvoicerFindFM},
  StockInvoiceStockInRfPS in 'Invoice\StockInvoiceStockInRfPS.pas' {StockInvoiceStockInRfFM},
  StockPayPS in 'Invoice\StockPayPS.pas' {StockPayFM},
  StockPayFindPS in 'Invoice\StockPayFindPS.pas' {StockPayFindFM},
  StockPayInvoiceRfPS in 'Invoice\StockPayInvoiceRfPS.pas' {StockPayInvoiceRfFM},
  StockMonthAccountPS in 'Invoice\StockMonthAccountPS.pas' {StockMonthAccountFM},
  StockPayQPS in 'Invoice\StockPayQPS.pas' {StockPayQFM},
  SaleOutPS in 'Ware\SaleOutPS.pas' {SaleOutFM},
  ProductOutPS in 'Ware\ProductOutPS.pas' {ProductOutFM},
  ItemBomQPS in 'BaseModule\ItemBomQPS.pas' {ItemBomQFM},
  StockInStockOrderRfPS in 'Ware\StockInStockOrderRfPS.pas' {StockInStockOrderRfFM},
  SaleSenderPS in 'Sale\SaleSenderPS.pas' {SaleSenderFM},
  SaleSenderQPS in 'Sale\SaleSenderQPS.pas' {SaleSenderQFM},
  SaleSenderSaleOrderRfPS in 'Sale\SaleSenderSaleOrderRfPS.pas' {SaleSenderSaleOrderRfFM},
  SaleOutSaleSenderRfPS in 'Ware\SaleOutSaleSenderRfPS.pas' {SaleOutSaleSenderRfFM},
  SaleOrderFindPS in 'Sale\SaleOrderFindPS.pas' {SaleOrderFindFM},
  WareItemQPS in 'BaseModule\WareItemQPS.pas' {WareItemQFM},
  ProOrderPS in 'Produce\ProOrderPS.pas' {ProOrderFM},
  ProOrderFindPS in 'Produce\ProOrderFindPS.pas' {ProOrderFindFM},
  SGeneralPS in 'BaseModule\SGeneralPS.pas' {SGeneralFM},
  RemarkGridPS in 'BaseModule\RemarkGridPS.pas' {RemarkGridFM},
  AssistInPS in 'Ware\AssistInPS.pas' {AssistInFM},
  AssistOutPS in 'Ware\AssistOutPS.pas' {AssistOutFM},
  SaleQPS in 'Sale\SaleQPS.pas' {SaleQFM},
  WKindQPS in 'BaseModule\WKindQPS.pas' {WKindQFM},
  AssistMovePS in 'Assist\AssistMovePS.pas' {AssistMoveFM},
  ItemMoveFindPS in 'WorkShop\ItemMoveFindPS.pas' {ItemMoveFindFM},
  ItemSaleQPS in 'Sale\ItemSaleQPS.pas' {ItemSaleQFM},
  AssistMoveInPS in 'Assist\AssistMoveInPS.pas' {AssistMoveInFM},
  StockOrderPS in 'Stock\StockOrderPS.pas' {StockOrderFM},
  ItemMovePS in 'Ware\ItemMovePS.pas' {ItemMoveFM},
  ControlPublicPS in 'Public\ControlPublicPS.pas',
  AMMsgPS in 'Public\AMMsgPS.pas',
  ASIMLib_TLB in 'Public\ASIMLib_TLB.pas',
  PreSendMsgPS in 'System\PreSendMsgPS.pas' {PreSendMsgFM},
  SysUserQPS in 'BaseModule\SysUserQPS.pas' {SysUserQFM},
  MainFormSetPS in 'System\MainFormSetPS.pas' {MainFormSetFM},
  SaleAccountAgeQPS in 'Invoice\SaleAccountAgeQPS.pas' {SaleAccountAgeQFM},
  AboutPS in 'System\AboutPS.pas' {AboutFM},
  StockAccountAgeQPS in 'Invoice\StockAccountAgeQPS.pas' {StockAccountAgeQFM},
  RemarkTextPS in 'Base\RemarkTextPS.pas' {RemarkTextFM},
  ItemSwitchPS in 'Ware\ItemSwitchPS.pas' {ItemSwitchFM},
  ItemSwitchFindPS in 'Ware\ItemSwitchFindPS.pas' {ItemSwitchFindFM},
  ItemSwitchQPS in 'Ware\ItemSwitchQPS.pas' {ItemSwitchQFM},
  MatOutProOrderRfPS in 'Ware\MatOutProOrderRfPS.pas' {MatOutProOrderRfFM},
  ProductInProOrderRfPS in 'Ware\ProductInProOrderRfPS.pas' {ProductInProOrderRfFM},
  BaseTechPS in 'Produce\BaseTechPS.pas' {BaseTechFM},
  ProOrderSaleOrderRfPS in 'Produce\ProOrderSaleOrderRfPS.pas' {ProOrderSaleOrderRfFM},
  ColorQPS in 'BaseModule\ColorQPS.pas' {ColorQFM},
  SafeStoreQPS in 'Ware\SafeStoreQPS.pas' {SafeStoreQFM},
  ShopModulePS in 'Public\ShopModulePS.pas' {ShopModuleFM},
  ShopMoveInPS in 'WorkShop\ShopMoveInPS.pas' {ShopMoveInFM},
  ShopMovePS in 'WorkShop\ShopMovePS.pas' {ShopMoveFM},
  ItemTechPS in 'WorkShop\ItemTechPS.pas' {ItemTechFM},
  BaseTechQPS in 'BaseModule\BaseTechQPS.pas' {BaseTechQFM},
  BOMMatOutItemQPS in 'Ware\BOMMatOutItemQPS.pas' {BOMMatOutItemQFM},
  ItemTechQPS in 'WorkShop\ItemTechQPS.pas' {ItemTechQFM},
  ProductInSaleOrderRfPS in 'Ware\ProductInSaleOrderRfPS.pas' {ProductInSaleOrderRfFM},
  BOMMatOutQPS in 'Ware\BOMMatOutQPS.pas' {BOMMatOutQFM},
  StockRecePS in 'Stock\StockRecePS.pas' {StockReceFM},
  StockReceFindPS in 'Stock\StockReceFindPS.pas' {StockReceFindFM},
  StockReceStockOrderRfPS in 'Stock\StockReceStockOrderRfPS.pas' {StockReceStockOrderRfFM},
  ProDispatchPS in 'Produce\ProDispatchPS.pas' {ProDispatchFM},
  ProDispatchFindPS in 'Produce\ProDispatchFindPS.pas' {ProDispatchFindFM},
  ProDispatchQPS in 'Produce\ProDispatchQPS.pas' {ProDispatchQFM},
  MatOutProDispatchRfPS in 'Ware\MatOutProDispatchRfPS.pas' {MatOutProDispatchRfFM},
  ProductInProDispatchRfPS in 'Ware\ProductInProDispatchRfPS.pas' {ProductInProDispatchRfFM},
  ProductInBomMatOutRfPS in 'Ware\ProductInBomMatOutRfPS.pas' {ProductInBomMatOutRfFM},
  ItemBomAnalysePS in 'BaseModule\ItemBomAnalysePS.pas' {ItemBomAnalyseFM},
  WareInOutSumQPS in 'Ware\WareInOutSumQPS.pas' {WareInOutSumQFM},
  AssistMoveQPS in 'Assist\AssistMoveQPS.pas' {AssistMoveQFM},
  ShopMoveQPS in 'WorkShop\ShopMoveQPS.pas' {ShopMoveQFM},
  AssistMoveInQPS in 'Assist\AssistMoveInQPS.pas' {AssistMoveInQFM},
  ShopMoveInQPS in 'WorkShop\ShopMoveInQPS.pas' {ShopMoveInQFM},
  EmpWorkRecordFindPS in 'Produce\EmpWorkRecordFindPS.pas' {EmpWorkRecordFindFM},
  EmpWorkRecordPS in 'Produce\EmpWorkRecordPS.pas' {EmpWorkRecordFM},
  EmpWorkRecordQPS in 'Produce\EmpWorkRecordQPS.pas' {EmpWorkRecordQFM},
  ProOrderQPS in 'Produce\ProOrderQPS.pas' {ProOrderQFM},
  OrderMatQPS in 'Produce\OrderMatQPS.pas' {OrderMatQFM},
  ProProcessQPS in 'Produce\ProProcessQPS.pas' {ProProcessQFM},
  ProDispatchProOrderRfPS in 'Produce\ProDispatchProOrderRfPS.pas' {ProDispatchProOrderRfFM},
  MatProDispatchRfPS in 'WorkShop\MatProDispatchRfPS.pas' {MatProDispatchRfFM},
  InProDispatchRfPS in 'WorkShop\InProDispatchRfPS.pas' {InProDispatchRfFM},
  AccNameQPS in 'Finance\AccNameQPS.pas' {AccNameQFM},
  CNAccNamePS in 'Finance\CNAccNamePS.pas' {CNAccNameFM},
  CNAccNameQPS in 'Finance\CNAccNameQPS.pas' {CNAccNameQFM},
  CNBankPS in 'Finance\CNBankPS.pas' {CNBankFM},
  CNBankQPS in 'Finance\CNBankQPS.pas' {CNBankQFM},
  CNCashPS in 'Finance\CNCashPS.pas' {CNCashFM},
  CNCashQPS in 'Finance\CNCashQPS.pas' {CNCashQFM},
  CNFirstPS in 'Finance\CNFirstPS.pas' {CNFirstFM},
  CNItemPS in 'Finance\CNItemPS.pas' {CNItemFM},
  CNItemQPS in 'Finance\CNItemQPS.pas' {CNItemQFM},
  CNMonthAccountPS in 'Finance\CNMonthAccountPS.pas' {CNMonthAccountFM},
  CWOtherPS in 'Finance\CWOtherPS.pas' {CWOtherFM},
  TechOutProDispatchRfPS in 'WorkShop\TechOutProDispatchRfPS.pas' {TechOutProDispatchRfFM},
  DelphiZXIngQRCode in 'RepExpand\DelphiZXIngQRCode.pas',
  frxExMemoView in 'RepExpand\frxExMemoView.pas',
  frxExMemoViewRtti in 'RepExpand\frxExMemoViewRtti.pas',
  frxQRCode in 'RepExpand\frxQRCode.pas',
  frxQRCodeRtti in 'RepExpand\frxQRCodeRtti.pas',
  CNMovePS in 'Finance\CNMovePS.pas' {CNMoveFM},
  CNMoveFindPS in 'Finance\CNMoveFindPS.pas' {CNMoveFindFM},
  AssistBackPS in 'Assist\AssistBackPS.pas' {AssistBackFM},
  AssistBackQPS in 'Assist\AssistBackQPS.pas' {AssistBackQFM},
  ShopBackPS in 'WorkShop\ShopBackPS.pas' {ShopBackFM},
  ShopBackQPS in 'WorkShop\ShopBackQPS.pas' {ShopBackQFM},
  AssistOutInQPS in 'Assist\AssistOutInQPS.pas' {AssistOutInQFM},
  BillModulePS in 'Public\BillModulePS.pas' {BillModuleFM},
  ReportModulePS in 'Public\ReportModulePS.pas' {ReportModuleFM},
  SysModulePS in 'Public\SysModulePS.pas' {SysModuleFM},
  CWModulePS in 'Public\CWModulePS.pas' {CWModuleFM},
  SaleOutQPS in 'ReportModule\SaleOutQPS.pas' {SaleOutQFM},
  SalePayQPS in 'ReportModule\SalePayQPS.pas' {SalePayQFM},
  ItemKindPS in 'BaseModule\ItemKindPS.pas' {ItemKindFM},
  StockInQPS in 'ReportModule\StockInQPS.pas' {StockInQFM};

{$R *.res}

begin

  if not bLogin then
  begin
    Application.Terminate;
    Exit;
  end;
  Application.Initialize;
  Application.Title := '∫„Ω›π‹¿Ì»Ìº˛';
  Application.CreateForm(TMainFM, MainFM);
  Application.MainFormOnTaskbar := True;
  Application.Run;

end.

